# Generated by Django 3.2.5 on 2022-04-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_auto_20210806_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="leads.category",
            ),
        ),
    ]
