# Generated by Django 3.2.5 on 2022-04-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_alter_lead_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.userprofile",
            ),
        ),
    ]
